/**
 * Turning a C2PA manifest into something a person can act on.
 *
 * The hard part here is not parsing, it is honesty. Content Credentials prove
 * exactly one thing: that a named signer attached a set of claims to this file
 * and the file has not changed since. They do not prove the claims are true,
 * and their absence proves nothing whatsoever.
 *
 * Every AI detector on the internet overstates what it knows. This file is
 * written so the product cannot do that: each reading carries an explicit
 * confidence, and the "no credentials" case says plainly that it means nothing.
 */

export type Verdict =
  | 'none'
  | 'tampered'
  | 'ai-generated'
  | 'ai-assisted'
  | 'camera'
  | 'edited'
  | 'signed';

export type Confidence = 'proven' | 'claimed' | 'unknown';

export interface Step {
  label: string;
  software: string | null;
  when: string | null;
}

export interface Signer {
  issuer: string | null;
  time: string | null;
  algorithm: string | null;
}

export interface Reading {
  verdict: Verdict;
  headline: string;
  explanation: string;
  confidence: Confidence;
  signer: Signer | null;
  /** The tool or device that claims to have produced the file. */
  producer: string | null;
  sourceLabel: string | null;
  steps: Step[];
  ingredients: string[];
  aiTraining: 'allowed' | 'not-allowed' | 'unstated';
  /** Whether the signing certificate itself is recognised. */
  signerTrust: 'trusted' | 'unrecognised' | 'expired' | 'revoked';
  warnings: string[];
}

/** Loose shape of what the SDK hands back, so this stays testable with plain objects. */
export interface ManifestStoreLike {
  active_manifest?: string | null;
  manifests?: Record<string, Record<string, unknown>>;
  validation_status?: Array<{ code?: string; explanation?: string }>;
  validation_results?: unknown;
}

/**
 * IPTC digital source types, in plain language.
 *
 * `aiLevel` is the part that matters: it separates "a machine generated this"
 * from "a person used a computer", a distinction the raw vocabulary blurs.
 */
export const SOURCE_TYPES: Record<string, { label: string; aiLevel: 'full' | 'partial' | 'none' }> = {
  'http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia': {
    label: 'Generated by an AI model',
    aiLevel: 'full',
  },
  'http://c2pa.org/digitalsourcetype/trainedAlgorithmicData': {
    label: 'Generated by an AI model',
    aiLevel: 'full',
  },
  'http://cv.iptc.org/newscodes/digitalsourcetype/compositeWithTrainedAlgorithmicMedia': {
    label: 'Combines real content with AI generated parts',
    aiLevel: 'partial',
  },
  'http://cv.iptc.org/newscodes/digitalsourcetype/algorithmicallyEnhanced': {
    label: 'Enhanced by an algorithm',
    aiLevel: 'partial',
  },
  'http://cv.iptc.org/newscodes/digitalsourcetype/digitalCapture': {
    label: 'Photographed with a camera',
    aiLevel: 'none',
  },
  'http://cv.iptc.org/newscodes/digitalsourcetype/computationalCapture': {
    label: 'Captured by a camera using computational processing',
    aiLevel: 'none',
  },
  'http://cv.iptc.org/newscodes/digitalsourcetype/negativeFilm': { label: 'Scanned from negative film', aiLevel: 'none' },
  'http://cv.iptc.org/newscodes/digitalsourcetype/positiveFilm': { label: 'Scanned from positive film', aiLevel: 'none' },
  'http://cv.iptc.org/newscodes/digitalsourcetype/print': { label: 'Scanned from a print', aiLevel: 'none' },
  'http://cv.iptc.org/newscodes/digitalsourcetype/screenCapture': { label: 'A screenshot', aiLevel: 'none' },
  'http://cv.iptc.org/newscodes/digitalsourcetype/digitalArt': { label: 'Digital art made by a person', aiLevel: 'none' },
  'http://cv.iptc.org/newscodes/digitalsourcetype/digitalCreation': {
    label: 'Created digitally by a person',
    aiLevel: 'none',
  },
  'http://cv.iptc.org/newscodes/digitalsourcetype/softwareImage': { label: 'Produced by software', aiLevel: 'none' },
  'http://cv.iptc.org/newscodes/digitalsourcetype/composite': { label: 'A composite of several sources', aiLevel: 'none' },
  'http://cv.iptc.org/newscodes/digitalsourcetype/compositeCapture': {
    label: 'A composite of several camera captures',
    aiLevel: 'none',
  },
  'http://cv.iptc.org/newscodes/digitalsourcetype/compositeSynthetic': {
    label: 'A composite built from synthetic parts',
    aiLevel: 'partial',
  },
  'http://cv.iptc.org/newscodes/digitalsourcetype/minorHumanEdits': { label: 'Minor edits by a person', aiLevel: 'none' },
  'http://cv.iptc.org/newscodes/digitalsourcetype/humanEdits': { label: 'Edited by a person', aiLevel: 'none' },
  'http://cv.iptc.org/newscodes/digitalsourcetype/algorithmicMedia': {
    label: 'Produced by an algorithm, not an AI model',
    aiLevel: 'none',
  },
  'http://c2pa.org/digitalsourcetype/empty': { label: 'Started from an empty canvas', aiLevel: 'none' },
};

/** Action labels in plain language. Anything unknown falls through unchanged. */
const ACTIONS: Record<string, string> = {
  'c2pa.created': 'Created',
  'c2pa.opened': 'Opened',
  'c2pa.edited': 'Edited',
  'c2pa.cropped': 'Cropped',
  'c2pa.resized': 'Resized',
  'c2pa.color_adjustments': 'Colour adjusted',
  'c2pa.drawing': 'Drawn on',
  'c2pa.filtered': 'Filter applied',
  'c2pa.placed': 'Another image placed into it',
  'c2pa.removed': 'Something removed',
  'c2pa.repackaged': 'Repackaged',
  'c2pa.transcoded': 'Converted to another format',
  'c2pa.converted': 'Converted',
  'c2pa.published': 'Published',
  'c2pa.redacted': 'Part redacted',
  'c2pa.watermarked': 'Watermarked',
  'c2pa.orientation': 'Rotated or flipped',
  'c2pa.unknown': 'An unrecorded change',
};

/**
 * Two very different kinds of failure, which must never be conflated.
 *
 * An integrity failure means the bytes changed after signing: the file is not
 * what was signed. A trust issue means the file is intact but the certificate
 * is not one we recognise. Reporting the second as the first accuses someone of
 * tampering when nothing was tampered with, which is the exact overreach this
 * tool exists to avoid.
 */
function isIntegrityFailure(code: string): boolean {
  if (/^signingCredential\.(untrusted|expired|revoked|notTrusted)$/i.test(code)) return false;
  return /\.(mismatch|missing|notValid|failed|malformed|outOfRange)$/i.test(code) || code.includes('.error');
}

function isTrustIssue(code: string): boolean {
  return /^signingCredential\.(untrusted|expired|revoked|notTrusted|invalid)$/i.test(code);
}

function asArray(value: unknown): unknown[] {
  return Array.isArray(value) ? value : [];
}

function softwareName(agent: unknown): string | null {
  if (typeof agent === 'string') return agent || null;
  if (agent && typeof agent === 'object') {
    const info = agent as { name?: string; version?: string };
    if (info.name) return info.version ? `${info.name} ${info.version}` : info.name;
  }
  return null;
}

function findAssertion(assertions: unknown[], label: string): Record<string, unknown> | null {
  for (const entry of assertions) {
    const a = entry as { label?: string; data?: unknown };
    if (a?.label === label || a?.label?.startsWith(`${label}.v`)) {
      return (a.data ?? {}) as Record<string, unknown>;
    }
  }
  return null;
}

const NO_CREDENTIALS: Reading = {
  verdict: 'none',
  headline: 'No Content Credentials found',
  explanation:
    'This file carries no provenance data. That does not mean it is fake, and it does not mean it is real. Most images on the internet have no credentials at all, because most cameras and apps do not add them yet. No conclusion can be drawn either way.',
  confidence: 'unknown',
  signer: null,
  producer: null,
  sourceLabel: null,
  steps: [],
  ingredients: [],
  aiTraining: 'unstated',
  signerTrust: 'trusted',
  warnings: [],
};

/**
 * Read a manifest store into a verdict.
 *
 * Pass null when the file has no credentials at all, which is what the SDK
 * returns and what most files will be.
 */
export function interpret(store: ManifestStoreLike | null): Reading {
  if (!store) return { ...NO_CREDENTIALS };

  const activeLabel = store.active_manifest ?? '';
  const manifest = (store.manifests ?? {})[activeLabel] ?? Object.values(store.manifests ?? {})[0];
  if (!manifest) return { ...NO_CREDENTIALS };

  const warnings: string[] = [];

  const signatureInfo = (manifest.signature_info ?? {}) as { issuer?: string; time?: string; alg?: string };
  const signer: Signer = {
    issuer: signatureInfo.issuer ?? null,
    time: signatureInfo.time ?? null,
    algorithm: signatureInfo.alg ?? null,
  };

  const generators = asArray(manifest.claim_generator_info) as Array<{ name?: string; version?: string }>;
  const producerFromGenerator = generators[0]?.name ?? (manifest.claim_generator as string | undefined) ?? null;

  const assertions = asArray(manifest.assertions);
  const actionData = findAssertion(assertions, 'c2pa.actions');
  const actions = asArray(actionData?.actions) as Array<Record<string, unknown>>;

  const steps: Step[] = actions.map((a) => ({
    label: ACTIONS[String(a.action ?? '')] ?? String(a.action ?? 'Unknown'),
    software: softwareName(a.softwareAgent),
    when: (a.when as string) ?? null,
  }));

  const ingredients = asArray(manifest.ingredients)
    .map((i) => (i as { title?: string }).title)
    .filter((t): t is string => Boolean(t));

  // Training permission, which is increasingly the reason people attach
  // credentials in the first place.
  const training = findAssertion(assertions, 'c2pa.training-mining');
  const entries = (training?.entries ?? {}) as Record<string, { use?: string }>;
  const trainingUse = entries['c2pa.ai_training']?.use ?? entries['c2pa.ai_generative_training']?.use;
  const aiTraining: Reading['aiTraining'] =
    trainingUse === 'notAllowed' ? 'not-allowed' : trainingUse === 'allowed' ? 'allowed' : 'unstated';

  const statuses = store.validation_status ?? [];

  const trustCodes = statuses.map((s) => s.code ?? '').filter(isTrustIssue);
  const signerTrust: Reading['signerTrust'] = trustCodes.some((c) => /revoked/i.test(c))
    ? 'revoked'
    : trustCodes.some((c) => /expired/i.test(c))
      ? 'expired'
      : trustCodes.length
        ? 'unrecognised'
        : 'trusted';

  if (signerTrust === 'unrecognised') {
    warnings.push(
      'The signing certificate is not on the known trust list. The file itself is intact and unaltered, but we cannot confirm who the signer is.',
    );
  } else if (signerTrust === 'expired') {
    warnings.push('The signing certificate had expired when this was checked.');
  } else if (signerTrust === 'revoked') {
    warnings.push('The signing certificate has been revoked. Treat these claims with suspicion.');
  }

  // Only a genuine integrity failure overrides the reading. If the bytes
  // changed after signing, nothing the manifest claims can be relied on.
  const failures = statuses.filter((s) => s.code && isIntegrityFailure(s.code));
  if (failures.length) {
    return {
      verdict: 'tampered',
      headline: 'The credentials do not match this file',
      explanation:
        'This file carries Content Credentials, but the cryptographic check failed. The image has been altered since it was signed, or the credentials were copied from a different file. Whatever the manifest claims cannot be relied on.',
      confidence: 'proven',
      signer,
      producer: producerFromGenerator,
      sourceLabel: null,
      steps,
      ingredients,
      aiTraining,
      signerTrust,
      warnings: [...warnings, ...failures.map((f) => f.explanation ?? f.code ?? 'Validation failed')],
    };
  }

  // The strongest AI signal anywhere in the action list wins, so an AI edit
  // applied to a camera original is not reported as a plain photograph.
  let strongest: { level: 'full' | 'partial' | 'none'; label: string } | null = null;
  let creationLevel: 'full' | 'partial' | 'none' | null = null;

  for (const action of actions) {
    const type = SOURCE_TYPES[String(action.digitalSourceType ?? '')];
    if (!type) continue;
    if (String(action.action) === 'c2pa.created') creationLevel = type.aiLevel;
    if (!strongest || rank(type.aiLevel) > rank(strongest.level)) {
      strongest = { level: type.aiLevel, label: type.label };
    }
  }

  const producer = softwareName(actions.find((a) => a.softwareAgent)?.softwareAgent) ?? producerFromGenerator;
  const signedBy = signer.issuer ? ` The claim is signed by ${signer.issuer}.` : '';

  if (strongest?.level === 'full') {
    return {
      verdict: 'ai-generated',
      headline: 'Declared as AI generated',
      explanation: `The credentials attached to this file declare that it was generated by an AI model.${signedBy} This is what the signer claims, not something we independently verified.`,
      confidence: 'claimed',
      signer,
      producer,
      sourceLabel: strongest.label,
      steps,
      ingredients,
      aiTraining,
      signerTrust,
      warnings,
    };
  }

  if (strongest?.level === 'partial') {
    return {
      verdict: 'ai-assisted',
      headline: 'Declared as partly AI',
      explanation: `The credentials declare that AI was involved in making or editing this image, but not that the whole image was generated.${signedBy} This is a signed claim rather than an independent finding.`,
      confidence: 'claimed',
      signer,
      producer,
      sourceLabel: strongest.label,
      steps,
      ingredients,
      aiTraining,
      signerTrust,
      warnings,
    };
  }

  if (creationLevel === 'none' && strongest) {
    return {
      verdict: 'camera',
      headline: 'Declared as captured, not generated',
      explanation: `The credentials declare this was captured or created without AI generation.${signedBy} It may still have been edited afterwards, and the steps below show what was recorded.`,
      confidence: 'claimed',
      signer,
      producer,
      sourceLabel: strongest.label,
      steps,
      ingredients,
      aiTraining,
      signerTrust,
      warnings,
    };
  }

  if (steps.length) {
    return {
      verdict: 'edited',
      headline: 'Edit history recorded',
      explanation: `The credentials record what was done to this file but do not state how it was originally made.${signedBy}`,
      confidence: 'claimed',
      signer,
      producer,
      sourceLabel: null,
      steps,
      ingredients,
      aiTraining,
      signerTrust,
      warnings,
    };
  }

  return {
    verdict: 'signed',
    headline: 'Signed, but it says little',
    explanation: `This file carries valid Content Credentials, but they record no origin and no edit history.${signedBy} It confirms who signed the file and that it has not changed since, and nothing more.`,
    confidence: 'claimed',
    signer,
    producer,
    sourceLabel: null,
    steps,
    ingredients,
    aiTraining,
    signerTrust,
    warnings,
  };
}

function rank(level: 'full' | 'partial' | 'none'): number {
  return level === 'full' ? 2 : level === 'partial' ? 1 : 0;
}
